name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
          bundler: default # Share cache with 'test' job

      - run: bundle exec standardrb

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-26.04, windows-2025]
        rspec: ["3.12", "3.13", "4.0"]
    env:
      BUNDLE_GEMFILE: gemfiles/rspec_${{ matrix.rspec }}.gemfile
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
          bundler: default # Test compatibility with Ruby-default bundler

      - run: bundle exec rake spec FORCE_COLOR=1

      - name: Dogfood
        run: bundle exec rake spec DOGFOOD=1 FORCE_COLOR=1
