name: CI

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        rspec: ["3.12", "3.13", "4.0"]
    env:
      BUNDLE_GEMFILE: gemfiles/rspec_${{ matrix.rspec }}.gemfile
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
          bundler: default # Test compatibility with Ruby-default bundler
      - run: bundle exec rspec --force-color
