name: Release

on:
  workflow_dispatch: {}

jobs:
  release:
    runs-on: ubuntu-26.04
    environment: release
    permissions:
      contents: write
      id-token: write
      attestations: write
      artifact-metadata: write
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: "4.0"
          bundler-cache: false # Prevent cache poisoning by pull requests

      - name: Get version number
        id: get_version
        run: |
          VERSION=$(ruby -r ./lib/rspec/capturing_formatter/version.rb -e "puts RSpec::CapturingFormatter::VERSION")
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      # Creates a tag too: vX.X.X
      - uses: rubygems/release-gem@7f9650160c1a4e7989fdc9855807bdbd421d8b6b # v1.4.1

      - name: Create attestation
        uses: actions/attest@1e69f48acb82d1966a394da916b4c1698aa569d6 # v4.2.2
        with:
          subject-path: "pkg/*.gem"

      - name: Create GitHub release
        run: gh release create "v$VERSION" pkg/*.gem --title "$VERSION" --notes-from-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.get_version.outputs.version }}
